### PR TITLE
I corrected the typography in branch fix/

### PR DESCRIPTION
**Pull request by castacu0**
I didn't notice that I wrote those words in Spanish.
Well, in fact, yes. I made that on purpose.
Now, I'm practicing with accents.
And several lines in a Pull Request.
As you see, the general name of this thing is the same Commit I previously made.

### CODE REVIEW

**Review by arturoacuna1 — CHANGES_REQUESTED** [review]
Instead of accents. Try using _HTML entities._

**Comment by castacu0** [comment]
I added what you recommended me to do.
Is that okay?

**Review by arturoacuna1 — APPROVED** [review]
LGTM

**Comment by arturoacuna1** [comment]
All good, let's finish this.

**Comment by arturoacuna1** [comment]
All good, let's finish this.
I recently deleted the branch fix/typo-in-frontend on GitHub
Pull it to your local

**Pull request merged**
